### PR TITLE
Single movie page

### PR DESCRIPTION
**Pull request by MarleneArvedahl**
Created a page to show information on single movies after clicking on a movie from the home page.

The MovieCard component is updated to handle clicks and navigate to the new single movie page with the movie data as state.

If you go directly to a single movie page without a state, the page fetches the movie data.

### CODE REVIEW

**Review by xievous — APPROVED** [review]
Great work om a saturday night

**Review by Smustus — CHANGES_REQUESTED** [review]
Great job!, Looking good, just seems to missing error handling in the try, catch block. (row 26-27 in FilmView.tsx)

**Review by Smustus — APPROVED** [review]
Looking good!

**Review by Kristoffergidd — APPROVED** [review]
good job!

**Review by Robert-Tyborn — APPROVED** [review]
great

**Pull request merged**
